const Discord = require("discord.js")
module.exports = {
    name: "tikm",

    //coś
    execute:async(message,args,client) => {
        
        const embed = new Discord.MessageEmbed()
        .setColor('RANDOM')
        .setTitle("TIKM")
        .setDescription("Toczeniem-nazywamy taki rodzaj obróbki skrawaniem, w którym ruch główny, obrotowy o prędkości vc wykonuje obrabiany napędzany od wrzeciona tokarki, a ruchy posuwowe, o prędkośći vf, wykonują najczęściej jednoostrzowe narzędzia zwane nożami tokarskimi \n\n\nrodzaje toczenia: wzdłużne,skośne,poprzeczne i planowanie, kształtowe, powierzchni kulistych, ze sterowaniem numerycznym CNC\n\n\nstruganie-jest sposobem obróbki, w którym zarówno ruch narzędzia jak i obrabianego przedmiotu są ruchami prostoliniowymi. Ze względu na to czy ruchem głównym jest ruch narzędzia czy przedmiotu, rozróżnia się struganie poprzeczne iw wzdłużne.\n\n\nw struganiu poprzecznym ruchem głównym jest ruch narzędzia, a ruchem posuwowym (skokowym) ruch przedmiotu (wraz ze stołem strugarki)\n\n\nStruganie poprzeczne może być poziome lub pionowe-   pionowe struganie poprzeczne nazywa się dłutowaniem\n\n\nW struganie wzdłużnym ruchem głównym jest euch przedmiotu (wraz ze stołem strugarki), a ruchem posuwowym (skokowym) ruch narzędzia\n\n\nWierceniem-kształtuje się otwory za pomocą narzędzi zwanych wiertłami.Wiercenie można realizować nie tylko na wiertarkach ale także na tkoarkach, wytaczarkach oraz na frezarkach. W wierceniu główne ruchy (obrotowe) może realizowac narzędzie (na weirtakach, wytaczarkach i frezarkach) lub przedmiot obravbiany(na tokarkach)\n\n\notwory można wykonywac za pomocą: wiercenia nieprzelotowego, wiercenia przelotowego, powiercania (wiercenia wtórnego), wiercenia trepanacyjnego a także: w pełnyym materiale,w niepełnym materiale\n\n\nFrezowanie jest to sposób obróbki, w którym wieloostrzowe narz edzue zawne frezem wykonuje ruch głównt obrotowy, a ruchy posuwowe wykonuje najczęściej przedmiot zamocowany na stole frrzarki.  Frezowanie po toczeniu to najczęściej spotykany sposób obróbki skrawaniem. Chechami charakterystycznimi frezowania jest: cykliczność pracy sotrza, zmienność przekroju warstwy skrawanej\n\n\nRozwiercanie-stosuje się w celu zwiększenia dokładności wymiaroko-kształtowej wierconych otworów (IT6 do IT10) i zmniejszania chropowatości powierzchni Ra=0,32  do 5um\n\n\npogłębianie - to powiększanie lub inne kształtowanie otworów na części ich długości,a także powierzchni zwewnętrznych, bezpośrednio przynależnych do otworu.\n\n\nprzeciąganie - jest sposobem obróbki skrawaniem, w krórym naddatek na obróbkę zdejmowany jest wieloostrzowym narzędziem zwanym przeciągaczem. Ostrza są tak ukształtowane, że każde następne jest wyższe lub szersze względem poprzedniego w kierunku prostopadłym do długości przciągacza o grubości warstwy skrawanej h. Odminą przeciągania jest przepychanie, w którym narzędzie jest przepychane przez otwór")
        return message.channel.send({embeds:[embed]})
    }
}